### ISSUE TITLE
Does this package still make use of `request`? 

### ISSUE THREAD

**Issue by gcampbell-msft** [tidev/node-appc#535]
There is a vulnerability in `request`, and it is no longer maintained. `request` is still pulled in through the package.json, but I don't see anything in the code referencing it or pulling it in through a `require` statement. Is this package still using it?

@m1ga @cb1kenobi

**Comment by gcampbell-msft** [comment]
@cb1kenobi That would be great! This would eliminate an issue for anyone who has vulnerability alerts.

**Comment by m1ga** [comment]
:smile: the you can review it: https://github.com/tidev/node-appc/pull/536

**Comment by cb1kenobi** [comment]
Boom! Done!
