### ISSUE TITLE
ios.js wrongly detects adhoc profiles

### ISSUE THREAD

**Issue by farfromrefug** [tidev/node-appc#67]
Hi Chris,

I dont think that script is used anymore, but older versions of the sdk still do.
There is a bug in that line
https://github.com/Akylas/node-appc/blob/master/lib/ios.js#L207
it should be 

```
} else if (new Buffer(p.DeveloperCertificates[0].value, 'base64').toString().indexOf('Distribution:') != -1) {
```

Could you fix it and commit it so that we get it when building a sdk?

Thanks

**Comment by cb1kenobi** [comment]
Closing as the iOS logic in node-appc has been moved to ioslib.
